/**
 * Deep Story Card deck — Minnesota / St. Croix valley knowledge for ages ~9–11.
 * Distractors are plausible misconceptions (same topic), not silly throwaways.
 */

import { shuffle, shuffleChoices } from "./data.js?v=race10";

export const STORY_DECK = [
  {
    id: "q-manoomin-name",
    topic: "Foodways",
    q: "Manoomin is an Ojibwe word. What living food does it name?",
    choices: [
      "Wild rice that grows in shallow lakes and rivers",
      "Maple sugar boiled from spring sap",
      "Dried corn stored for winter",
      "Blueberries gathered in midsummer",
    ],
    a: 0,
    hint: "It is sometimes called the 'good berry' and is still harvested by canoe.",
    teach: "Manoomin (wild rice) is a sacred and important food for Ojibwe communities. Respectful harvest leaves plants to reseed.",
  },
  {
    id: "q-birchbark",
    topic: "Travel",
    q: "Why were birchbark canoes especially good for the St. Croix water roads?",
    choices: [
      "They were light, strong, and could be carried on portages",
      "They were heavier than dugout logs, so they tracked straighter",
      "They needed deep ocean water to stay upright",
      "They were built only for one-person racing events",
    ],
    a: 0,
    hint: "Think about carrying a boat between two lakes.",
    teach: "Birchbark canoes were engineered for rivers and lakes — tough enough for travel, light enough to portage.",
  },
  {
    id: "q-portage-def",
    topic: "Travel",
    q: "What does a portage mean on a canoe journey?",
    choices: [
      "Carrying the canoe and gear over land between waters",
      "Paddling upstream against the current all day",
      "Camping overnight beside a single lake",
      "Trading furs at a riverside post",
    ],
    a: 0,
    hint: "It connects two waters that don't join by water.",
    teach: "Portages linked Minnesota's water highways. Teamwork and planning mattered as much as paddling.",
  },
  {
    id: "q-maple-season",
    topic: "Foodways",
    q: "In what season do Dakota and Ojibwe families traditionally gather for maple sugaring?",
    choices: [
      "Early spring, when warm days follow freezing nights",
      "Late summer, when berries are thickest",
      "Midwinter, when lakes are fully frozen",
      "Early autumn, right after wild-rice harvest",
    ],
    a: 0,
    hint: "Sap runs when freeze–thaw cycles wake the trees.",
    teach: "Maple sugaring is a living spring tradition — sap becomes sugar and syrup that feed families and gatherings.",
  },
  {
    id: "q-glaciers",
    topic: "Land",
    q: "What chiefly shaped many of Minnesota's lakes and the St. Croix valley?",
    choices: [
      "Glaciers and meltwater during the Ice Age",
      "Volcanic eruptions under the lakes",
      "Wind carving dunes into basins",
      "Modern dams built in the last century",
    ],
    a: 0,
    hint: "Huge sheets of slow ice once covered the region.",
    teach: "Glacial ice carved basins; meltwater rivers helped shape the St. Croix valley we travel today.",
  },
  {
    id: "q-pictograph-care",
    topic: "Care",
    q: "What is the respectful way to visit real cliff pictographs?",
    choices: [
      "Look with your eyes — do not touch the paint",
      "Gently rub the rock to clear dust from the lines",
      "Trace the outlines with water so they show better in photos",
      "Take a small flake of paint if the site looks damaged already",
    ],
    a: 0,
    hint: "Skin oils can damage ancient paint.",
    teach: "Rock art sites are treasures. Looking without touching protects them for future generations.",
  },
  {
    id: "q-bdote",
    topic: "Places",
    q: "Bdote, where great rivers meet near present-day Minneapolis–Saint Paul, is…",
    choices: [
      "A place of deep meaning to the Dakota people",
      "A French fort name with no older meaning",
      "A modern nickname for the airport area only",
      "A fur-company warehouse district invented in the 1900s",
    ],
    a: 0,
    hint: "It mattered long before forts or cities.",
    teach: "Bdote is sacred and significant to Dakota people. Honest history remembers who was here first.",
  },
  {
    id: "q-pipestone",
    topic: "Places",
    q: "How is the soft red stone from Pipestone traditionally treated?",
    choices: [
      "As special and deeply respected, used for sacred pipes",
      "As ordinary building stone for pioneer farmhouses",
      "As trail gravel crushed for wagon roads",
      "As a common toy material for children's games",
    ],
    a: 0,
    hint: "Many nations traveled to quarry in peace.",
    teach: "Pipestone quarries are still used by Native people. The stone traveled trade routes across the region.",
  },
  {
    id: "q-fur-trade",
    topic: "Exchange",
    q: "By the fur-trade era, Native nations in this region were…",
    choices: [
      "Skilled traders with long-standing trade networks",
      "Newcomers who had never exchanged goods before",
      "Isolated groups with no contact beyond one village",
      "Dependent only on European goods from the start",
    ],
    a: 0,
    hint: "Copper, shells, and other goods had moved for centuries.",
    teach: "The fur trade was an exchange between nations — not an 'empty land' waiting to be found.",
  },
  {
    id: "q-archaeology",
    topic: "Care",
    q: "What does careful archaeology teach kids to do?",
    choices: [
      "Dig only with permission, record context, and respect sacred places",
      "Collect arrowheads from any field to keep at home",
      "Move burial objects into museums without asking anyone",
      "Focus on treasure value more than where an object was found",
    ],
    a: 0,
    hint: "Where something is found can matter as much as the object.",
    teach: "Real archaeology uses science, permission, and respect — and never harms burial mounds or sacred sites.",
  },
  {
    id: "q-anishinaabe",
    topic: "People",
    q: "Ojibwe people are also known as Anishinaabe. What does that remind us?",
    choices: [
      "They are living cultures with languages, families, and traditions today",
      "Their history ended when the fur trade closed",
      "They are one past culture with no modern communities",
      "The name only appears in old expedition journals",
    ],
    a: 0,
    hint: "Culture is not only 'the past.'",
    teach: "Dakota and Ojibwe cultures are living. Learning with respect keeps knowledge moving forward.",
  },
  {
    id: "q-dakota-homeland",
    topic: "People",
    q: "The St. Croix valley is part of the homeland of which peoples (among others)?",
    choices: [
      "Dakota and Ojibwe (Anishinaabe) peoples",
      "Only Voyageurs from Montreal",
      "Only settlers who arrived after statehood",
      "Only Lakota communities of the far western plains",
    ],
    a: 0,
    hint: "Two major Nations have deep roots here.",
    teach: "This valley holds Dakota and Ojibwe homelands, water roads, foodways, and stories.",
  },
  {
    id: "q-headwaters",
    topic: "Land",
    q: "Where does a river like the St. Croix begin?",
    choices: [
      "At its headwaters — often a spring, lake, or small stream",
      "At the Mississippi, then flowing backward to the north",
      "At the ocean mouth, then inland toward the hills",
      "At the widest bend in the middle of its course",
    ],
    a: 0,
    hint: "The 'head' of the river is its source.",
    teach: "Protecting headwaters helps keep the whole river healthy downstream.",
  },
  {
    id: "q-seasonal-round",
    topic: "Foodways",
    q: "Why did many families move with the seasons along these water roads?",
    choices: [
      "Different places offered maple, rice, fish, game, and gatherings at different times",
      "They were required to move whenever a fort changed commanders",
      "Canoes could only be used in one season per year",
      "Each family could own only one campsite forever",
    ],
    a: 0,
    hint: "Food and ceremony follow the year's cycle.",
    teach: "A seasonal round — sugarbush, ricing, hunting, fishing — shaped travel and community life.",
  },
  {
    id: "q-wild-rice-care",
    topic: "Foodways",
    q: "What is one idea behind a respectful manoomin harvest?",
    choices: [
      "Take what you need and leave plants so beds can grow again",
      "Harvest every stalk so competitors cannot return next year",
      "Pull plants up by the roots to get the most grain",
      "Drain shallow lakes so rice can be cut with farm machines",
    ],
    a: 0,
    hint: "Living with the land, not emptying it.",
    teach: "Knockers and canoes can harvest gently so rice reseeds — a practice of care.",
  },
  {
    id: "q-water-roads",
    topic: "Travel",
    q: "Before highways, how did people often travel and connect across this region?",
    choices: [
      "On lakes and rivers — the water roads — by canoe",
      "Mostly on railroad lines built for timber only",
      "Mostly on wagon roads that ignored the rivers",
      "Mostly by walking ridge trails and avoiding water",
    ],
    a: 0,
    hint: "Think of birchbark and paddles.",
    teach: "Water roads linked families, trade, diplomacy, and stories for thousands of years.",
  },
  {
    id: "q-language-alive",
    topic: "People",
    q: "Why might a game ask you to hear words like Boozhoo or manoomin?",
    choices: [
      "Because Indigenous languages are living and worth learning with care",
      "Because the words are only used in historical reenactments",
      "Because English replaced every other language here long ago",
      "Because they are place-holder sounds with no real meaning",
    ],
    a: 0,
    hint: "Greeting and food words carry culture.",
    teach: "Hearing and saying words respectfully is one small way to honor living languages.",
  },
  {
    id: "q-trade-goods",
    topic: "Exchange",
    q: "Which goods moved along regional trade networks long ago?",
    choices: [
      "Things like copper, shells, pipestone, furs, and food knowledge",
      "Only European metal tools after contact",
      "Only wild rice, with no other materials exchanged",
      "Only stone for building forts along the river",
    ],
    a: 0,
    hint: "Trade is older than the fur-trade posts kids read about first.",
    teach: "Indigenous trade networks were wide and skilled long before European traders arrived.",
  },
  {
    id: "q-mounds-respect",
    topic: "Care",
    q: "If you see burial mounds or marked sacred places, what should you do?",
    choices: [
      "Look from a respectful distance and do not dig or climb on them",
      "Walk the tops carefully if a path already crosses them",
      "Probe with a stick to see if anything is buried nearby",
      "Collect surface pottery shards as long as you don't dig deep",
    ],
    a: 0,
    hint: "Sacred places are not playgrounds or dig sites.",
    teach: "Protecting burial and sacred sites is part of respecting living Nations and ancestors.",
  },
  {
    id: "q-st-croix-name",
    topic: "Places",
    q: "The St. Croix River forms part of the border between which two states?",
    choices: [
      "Minnesota and Wisconsin",
      "Minnesota and Iowa",
      "Wisconsin and Michigan",
      "Minnesota and North Dakota",
    ],
    a: 0,
    hint: "It flows toward the Mississippi between two Midwestern neighbors.",
    teach: "The St. Croix valley spans communities in Minnesota and Wisconsin — and older Indigenous geographies too.",
  },
  {
    id: "q-namekagon",
    topic: "Places",
    q: "The Namekagon is best described as…",
    choices: [
      "A clear sister river that joins the St. Croix water road system",
      "The main stem of the Mississippi above Minneapolis",
      "A canal dug to connect Lake Superior to the Twin Cities",
      "A reservoir created only for modern hydroelectric power",
    ],
    a: 0,
    hint: "Canoe country north and east of parts of the St. Croix.",
    teach: "Tributaries like the Namekagon extended the web of travel, fishing, and family connection.",
  },
  {
    id: "q-ice-age-time",
    topic: "Land",
    q: "About when did the last major Ice Age glaciers reshape this landscape?",
    choices: [
      "Tens of thousands of years ago",
      "A few hundred years before statehood",
      "During the height of the fur trade",
      "Only after European settlement began",
    ],
    a: 0,
    hint: "Deep time — longer than written history here.",
    teach: "Geology sets the stage; human stories then fill the valley with meaning.",
  },
  {
    id: "q-helper-listen",
    topic: "Care",
    q: "When learning about Dakota or Ojibwe teachings in school or games, a good habit is…",
    choices: [
      "Listen carefully, avoid stereotypes, and remember cultures are living",
      "Treat every story as the same for all Native Nations",
      "Use sacred ceremonies as costume ideas for plays",
      "Assume the only accurate sources are old explorer diaries",
    ],
    a: 0,
    hint: "Respect > performance.",
    teach: "There are many Nations and teachings. Curiosity plus humility is the right trail gear.",
  },
  {
    id: "q-canoe-family",
    topic: "Travel",
    q: "Who typically traveled the water roads?",
    choices: [
      "Families, traders, diplomats, and messengers — whole communities on the move",
      "Only young men sent alone on long scouting trips",
      "Only European surveyors mapping the border",
      "Only hunters who never brought relatives or goods",
    ],
    a: 0,
    hint: "Travel connected kinship and diplomacy.",
    teach: "Canoe routes carried people and relationships, not just cargo.",
  },
  {
    id: "q-fish-stew",
    topic: "Foodways",
    q: "Why are lakes and rivers central to food stories here?",
    choices: [
      "Fish, wild rice, water plants, and travel all depend on healthy waters",
      "Water was mainly used for washing, not for food",
      "Most calories came from ocean fishing far from Minnesota",
      "Rivers were avoided because they spoiled stored meat",
    ],
    a: 0,
    hint: "Water = life + movement + harvest.",
    teach: "Caring for water protects foodways and future travelers.",
  },
  {
    id: "q-council-race",
    topic: "Stories",
    q: "In this race, reaching the Council of Stories means…",
    choices: [
      "You carried learning along the trail and finished first with true answers",
      "You skipped every question and only rolled high numbers",
      "You collected physical rocks called Story Stones from the map",
      "You defeated the CPU by lowering its health to zero",
    ],
    a: 0,
    hint: "Stay on spaces by answering; bounce back if you miss.",
    teach: "The race rewards careful knowledge — not just lucky dice.",
  },
  {
    id: "q-maple-manoomin",
    topic: "Foodways",
    q: "Maple sugar and manoomin are important here. Which statement is true?",
    choices: [
      "They are part of living food traditions, not only museum exhibits",
      "They were invented solely by French traders in the 1700s",
      "They are harvested only in midwinter under thick ice",
      "They replaced hunting and fishing entirely in this valley",
    ],
    a: 0,
    hint: "People still sugar and rice today.",
    teach: "Food traditions continue in families and communities across the seasons.",
  },
  {
    id: "q-fort-context",
    topic: "History",
    q: "When you hear about forts near river meetings, what should you also remember?",
    choices: [
      "Indigenous places and meanings were already there",
      "The land had no people until the fort was built",
      "River names began only after forts were mapped",
      "Forts are the only sites worth studying in the valley",
    ],
    a: 0,
    hint: "Start the timeline earlier.",
    teach: "Forts are one layer. Homelands, treaties, and living Nations are the deeper story.",
  },
  {
    id: "q-beaver",
    topic: "Land",
    q: "Beavers matter in this landscape because they…",
    choices: [
      "Build dams that change waterways — and their fur was also traded",
      "Were important only as story characters, not real animals here",
      "Lived only on the Great Plains, never in these wetlands",
      "Were hunted solely for meat and never affected rivers",
    ],
    a: 0,
    hint: "Engineers of wetlands + fur trade history.",
    teach: "Animals shape land and stories; the fur trade also entangled human economies.",
  },
  {
    id: "q-winter",
    topic: "Seasons",
    q: "How did winter change travel and life on the trail?",
    choices: [
      "Snow and ice meant different routes, foods, and skills — like snowshoes and stored foods",
      "Travel stopped completely until the spring thaw",
      "Canoes became the main winter vehicle on frozen lakes",
      "Families moved south permanently and never returned",
    ],
    a: 0,
    hint: "Seasons demand different knowledge.",
    teach: "Winter skills and stored foods were as important as summer paddling.",
  },
  {
    id: "q-treaty-aware",
    topic: "History",
    q: "Treaties between Native Nations and the U.S. are best understood as…",
    choices: [
      "Serious nation-to-nation agreements with lasting importance",
      "Informal friendships that never carried legal weight",
      "Temporary camping permits for one hunting season",
      "Documents that ended all Native rights the day they were signed",
    ],
    a: 0,
    hint: "Treaties are law and living politics — learn more with teachers and elders.",
    teach: "Treaty history is complex. This game only opens the door — keep learning with trusted sources.",
  },
  {
    id: "q-loon",
    topic: "Land",
    q: "The common loon's call is famous on northern lakes. What does that remind us?",
    choices: [
      "Healthy lakes support wildlife people have long lived beside",
      "Loons were brought here only after state parks opened",
      "Birds avoid lakes that humans have ever used",
      "Soundscapes matter less than road traffic for lake health",
    ],
    a: 0,
    hint: "Soundscape of the north woods.",
    teach: "People and animals share these waters — stewardship matters.",
  },
  {
    id: "q-copper",
    topic: "Exchange",
    q: "Native peoples of the Great Lakes region worked copper long ago. What does that show?",
    choices: [
      "Advanced skill, trade, and technology were present for a very long time",
      "Metalwork in this region began only after 1900",
      "Copper was ignored until European traders arrived",
      "Stone tools were never used beside metal in the same era",
    ],
    a: 0,
    hint: "Ancient mines and trade goods tell a deep timeline.",
    teach: "Innovation and trade are part of Indigenous history in this region.",
  },
  {
    id: "q-women-rice",
    topic: "Foodways",
    q: "Harvesting and processing manoomin often involves…",
    choices: [
      "Community knowledge, care, and shared work across generations",
      "A single secret method known to only one family forever",
      "Machines that replaced all human teaching generations ago",
      "Guesswork each year with no tradition to follow",
    ],
    a: 0,
    hint: "Knowledge is taught and practiced together.",
    teach: "Foodways are community practices — skills passed with patience.",
  },
  {
    id: "q-maps",
    topic: "Travel",
    q: "Indigenous maps and knowledge of routes were often carried how?",
    choices: [
      "In memory, story, song, and teaching — sometimes also in drawings",
      "Only on printed paper maps sold at trading posts",
      "Only through European surveyors' notebooks",
      "Not at all — travelers relied on chance alone",
    ],
    a: 0,
    hint: "Oral and practiced knowledge is powerful.",
    teach: "Knowing water roads was (and is) a sophisticated skill.",
  },
  {
    id: "q-kids",
    topic: "People",
    q: "Kids on the historical trail would most likely have…",
    choices: [
      "Learned skills by helping family — paddling, gathering, listening to stories",
      "Stayed away from foodwork until adulthood",
      "Learned only from books written in distant cities",
      "Traveled alone without any teaching from relatives",
    ],
    a: 0,
    hint: "Learning by doing beside elders and relatives.",
    teach: "Young people have always been part of the seasonal round and story-carrying.",
  },
  {
    id: "q-mississippi-link",
    topic: "Places",
    q: "The St. Croix joins a larger river system that includes…",
    choices: [
      "The Mississippi River",
      "The Missouri River only, never the Mississippi",
      "Lake Superior with no link southward",
      "The Red River of the North exclusively",
    ],
    a: 0,
    hint: "Southward waters gather into a famous North American river.",
    teach: "Local valleys connect to continental water roads — geography is relationship.",
  },
  {
    id: "q-stereotype",
    topic: "Care",
    q: "Which choice avoids a harmful stereotype?",
    choices: [
      "Native Nations are diverse, modern, and rooted in specific places and languages",
      "All Native people share one culture and live only in the past",
      "Native cultures are mainly costumes and sports mascots",
      "Native history begins only when settlers write it down",
    ],
    a: 0,
    hint: "Specific > generic.",
    teach: "This game focuses on Dakota and Ojibwe connections to the St. Croix — still only a beginning.",
  },
  {
    id: "q-carry-knowledge",
    topic: "Stories",
    q: "Carrying knowledge to the Council is most like…",
    choices: [
      "Portaging a canoe — careful work you share so others can travel too",
      "Hiding answers so rivals cannot learn anything",
      "Skipping questions to move faster on the board",
      "Collecting points with no need to remember the teach text",
    ],
    a: 0,
    hint: "Portage = carry canoe + carry stories.",
    teach: "You win by learning and sharing, not by erasing others' stories.",
  },
  {
    id: "q-energy",
    topic: "Travel",
    q: "Why did travelers care about food energy on a portage?",
    choices: [
      "Carrying canoes is hard work — meals and rest keep people going",
      "Portages were short flat paths that needed no food planning",
      "Food was carried only for trade, never for the travelers themselves",
      "Energy mattered on water but never on overland carries",
    ],
    a: 0,
    hint: "Heavy canoe + muddy trail = teamwork and snacks.",
    teach: "Logistics — food, rest, and shared labor — made long journeys possible.",
  },
];

export function drawStoryCard(usedIds = []) {
  const used = new Set(usedIds);
  let pool = STORY_DECK.filter((c) => !used.has(c.id));
  let reshuffled = false;
  if (!pool.length) {
    pool = [...STORY_DECK];
    reshuffled = true;
  }
  const card = shuffle(pool)[0];
  const mixed = shuffleChoices(card.choices, card.a);
  return {
    card: {
      id: card.id,
      topic: card.topic,
      q: card.q,
      hint: card.hint,
      teach: card.teach,
      choices: mixed.choices,
      answer: mixed.answer,
    },
    usedIds: reshuffled ? [card.id] : [...usedIds, card.id],
    reshuffled,
  };
}

export function deckRemaining(usedIds = []) {
  return Math.max(0, STORY_DECK.length - usedIds.length);
}
