/**
 * Deep Story Card deck — Minnesota / St. Croix valley knowledge for ages ~9–11.
 * Questions are drawn at random; each card id is tracked so it never repeats
 * in a run until the deck is exhausted (then it reshuffles).
 */

import { shuffle, shuffleChoices } from "./data.js";

export const STORY_DECK = [
  {
    id: "q-manoomin-name",
    topic: "Foodways",
    q: "Manoomin is an Ojibwe word. What living food does it name?",
    choices: ["Wild rice that grows in shallow lakes and rivers", "Only corn grown in deserts", "Ocean seaweed", "A kind of maple candy"],
    a: 0,
    hint: "It is sometimes called the 'good berry' and is still harvested today.",
    teach: "Manoomin (wild rice) is a sacred and important food for Ojibwe communities. Respectful harvest leaves plants to reseed.",
  },
  {
    id: "q-birchbark",
    topic: "Travel",
    q: "Why were birchbark canoes especially good for the St. Croix water roads?",
    choices: ["They were light, strong, and could be carried on portages", "They were made of iron and never floated", "They had motors", "They only worked on oceans"],
    a: 0,
    hint: "Think about carrying a boat between two lakes.",
    teach: "Birchbark canoes were engineered for rivers and lakes — tough enough for travel, light enough to portage.",
  },
  {
    id: "q-portage-def",
    topic: "Travel",
    q: "What does a portage mean on a canoe journey?",
    choices: ["Carrying the canoe and gear over land between waters", "Sleeping inside the canoe overnight", "Racing canoes for prizes", "Painting designs on the canoe"],
    a: 0,
    hint: "It connects two waters that don't join by water.",
    teach: "Portages linked Minnesota's water highways. Teamwork and planning mattered as much as paddling.",
  },
  {
    id: "q-maple-season",
    topic: "Foodways",
    q: "In what season do Dakota and Ojibwe families traditionally gather for maple sugaring?",
    choices: ["Early spring, when warm days follow freezing nights", "The hottest weeks of midsummer", "Late autumn after the first snow only", "Any random week in the year"],
    a: 0,
    hint: "Sap runs when freeze–thaw cycles wake the trees.",
    teach: "Maple sugaring is a living spring tradition — sap becomes sugar and syrup that feed families and gatherings.",
  },
  {
    id: "q-glaciers",
    topic: "Land",
    q: "What chiefly shaped many of Minnesota's lakes and the St. Croix valley?",
    choices: ["Glaciers and meltwater during the Ice Age", "A single modern flood last year", "Volcanoes under every lake", "People digging with steam shovels"],
    a: 0,
    hint: "Huge sheets of slow ice once covered the region.",
    teach: "Glacial ice carved basins; meltwater rivers helped shape the St. Croix valley we travel today.",
  },
  {
    id: "q-pictograph-care",
    topic: "Care",
    q: "What is the respectful way to visit real cliff pictographs?",
    choices: ["Look with your eyes — do not touch the paint", "Trace them with markers so they stay bright", "Chip a small piece to keep as a souvenir", "Repaint them in brighter colors"],
    a: 0,
    hint: "Skin oils can damage ancient paint.",
    teach: "Rock art sites are treasures. Looking without touching protects them for future generations.",
  },
  {
    id: "q-bdote",
    topic: "Places",
    q: "Bdote, where great rivers meet near present-day Minneapolis–Saint Paul, is…",
    choices: ["A place of deep meaning to the Dakota people", "An empty parking lot with no history", "A brand-new lake made last century", "A made-up name from a video game"],
    a: 0,
    hint: "It mattered long before forts or cities.",
    teach: "Bdote is sacred and significant to Dakota people. Honest history remembers who was here first.",
  },
  {
    id: "q-pipestone",
    topic: "Places",
    q: "How is the soft red stone from Pipestone traditionally treated?",
    choices: ["As special and deeply respected, used for sacred pipes", "As ordinary gravel for roads", "As a toy to trade for candy", "As something to sell online without care"],
    a: 0,
    hint: "Many nations traveled to quarry in peace.",
    teach: "Pipestone quarries are still used by Native people. The stone traveled trade routes across the region.",
  },
  {
    id: "q-fur-trade",
    topic: "Exchange",
    q: "By the fur-trade era, Native nations in this region were…",
    choices: ["Skilled traders with long-standing trade networks", "Brand new to the area with no trade skills", "Uninterested in any exchange", "Living alone with no neighbors"],
    a: 0,
    hint: "Copper, shells, and other goods had moved for centuries.",
    teach: "The fur trade was an exchange between nations — not an 'empty land' waiting to be found.",
  },
  {
    id: "q-archaeology",
    topic: "Care",
    q: "What does careful archaeology teach kids to do?",
    choices: ["Dig only with permission, record context, and respect sacred places", "Dig anywhere for treasure to keep", "Move bones and sacred objects home", "Ignore where an object was found"],
    a: 0,
    hint: "Where something is found can matter as much as the object.",
    teach: "Real archaeology uses science, permission, and respect — and never harms burial mounds or sacred sites.",
  },
  {
    id: "q-anishinaabe",
    topic: "People",
    q: "Ojibwe people are also known as Anishinaabe. What does that remind us?",
    choices: ["They are living cultures with languages, families, and traditions today", "They only exist in old museum photos", "They left Minnesota forever long ago", "They were invented for school textbooks"],
    a: 0,
    hint: "Culture is not only 'the past.'",
    teach: "Dakota and Ojibwe cultures are living. Learning with respect keeps knowledge moving forward.",
  },
  {
    id: "q-dakota-homeland",
    topic: "People",
    q: "The St. Croix valley is part of the homeland of which peoples (among others)?",
    choices: ["Dakota and Ojibwe (Anishinaabe) peoples", "Only explorers from Europe", "Only animals with no human history", "A single family that arrived last week"],
    a: 0,
    hint: "Two major Nations have deep roots here.",
    teach: "This valley holds Dakota and Ojibwe homelands, water roads, foodways, and stories.",
  },
  {
    id: "q-headwaters",
    topic: "Land",
    q: "Where does a river like the St. Croix begin?",
    choices: ["At its headwaters — often a spring, lake, or small stream", "Only at the ocean", "In the exact middle of its course", "Nowhere — rivers have no beginning"],
    a: 0,
    hint: "The 'head' of the river is its source.",
    teach: "Protecting headwaters helps keep the whole river healthy downstream.",
  },
  {
    id: "q-seasonal-round",
    topic: "Foodways",
    q: "Why did many families move with the seasons along these water roads?",
    choices: ["Different places offered maple, rice, fish, game, and gatherings at different times", "They were lost and could not find one home", "Laws forced them to move every Monday", "Canoes only floated in winter"],
    a: 0,
    hint: "Food and ceremony follow the year's cycle.",
    teach: "A seasonal round — sugarbush, ricing, hunting, fishing — shaped travel and community life.",
  },
  {
    id: "q-wild-rice-care",
    topic: "Foodways",
    q: "What is one idea behind a respectful manoomin harvest?",
    choices: ["Take what you need and leave plants so beds can grow again", "Harvest every plant until the lake is empty", "Use machines that rip out the roots", "Keep the rice only for display, never food"],
    a: 0,
    hint: "Living with the land, not emptying it.",
    teach: "Knockers and canoes can harvest gently so rice reseeds — a practice of care.",
  },
  {
    id: "q-water-roads",
    topic: "Travel",
    q: "Before highways, how did people often travel and connect across this region?",
    choices: ["On lakes and rivers — the water roads — by canoe", "Only by airplane", "Only by snowmobile year-round", "By digging tunnels under every lake"],
    a: 0,
    hint: "Think of birchbark and paddles.",
    teach: "Water roads linked families, trade, diplomacy, and stories for thousands of years.",
  },
  {
    id: "q-language-alive",
    topic: "People",
    q: "Why might a game ask you to hear words like Boozhoo or manoomin?",
    choices: ["Because Indigenous languages are living and worth learning with care", "Because the words are fake sound effects", "Because English is the only real language here", "Because they are secret codes for pirates"],
    a: 0,
    hint: "Greeting and food words carry culture.",
    teach: "Hearing and saying words respectfully is one small way to honor living languages.",
  },
  {
    id: "q-trade-goods",
    topic: "Exchange",
    q: "Which goods moved along regional trade networks long ago?",
    choices: ["Things like copper, shells, pipestone, furs, and food knowledge", "Only plastic toys", "Only gasoline", "Nothing — nobody traded"],
    a: 0,
    hint: "Trade is older than the fur-trade posts kids read about first.",
    teach: "Indigenous trade networks were wide and skilled long before European traders arrived.",
  },
  {
    id: "q-mounds-respect",
    topic: "Care",
    q: "If you see burial mounds or marked sacred places, what should you do?",
    choices: ["Look from a respectful distance and do not dig or climb on them", "Dig for artifacts to sell", "Ride bikes over them for fun", "Build a fort on top"],
    a: 0,
    hint: "Sacred places are not playgrounds or dig sites.",
    teach: "Protecting burial and sacred sites is part of respecting living Nations and ancestors.",
  },
  {
    id: "q-st-croix-name",
    topic: "Places",
    q: "The St. Croix River forms part of the border between which two states?",
    choices: ["Minnesota and Wisconsin", "Minnesota and California", "Florida and Georgia", "Alaska and Hawaii"],
    a: 0,
    hint: "It flows toward the Mississippi between two Midwestern neighbors.",
    teach: "The St. Croix valley spans communities in Minnesota and Wisconsin — and older Indigenous geographies too.",
  },
  {
    id: "q-namekagon",
    topic: "Places",
    q: "The Namekagon is best described as…",
    choices: ["A clear sister river that joins the St. Croix water road system", "A desert canyon in Arizona", "An ocean current", "A mountain in the Rockies"],
    a: 0,
    hint: "Canoe country north and east of parts of the St. Croix.",
    teach: "Tributaries like the Namekagon extended the web of travel, fishing, and family connection.",
  },
  {
    id: "q-ice-age-time",
    topic: "Land",
    q: "About when did the last major Ice Age glaciers reshape this landscape?",
    choices: ["Tens of thousands of years ago", "Last Tuesday", "Exactly 100 years ago", "Before Earth had water"],
    a: 0,
    hint: "Deep time — longer than written history here.",
    teach: "Geology sets the stage; human stories then fill the valley with meaning.",
  },
  {
    id: "q-helper-listen",
    topic: "Care",
    q: "When learning about Dakota or Ojibwe teachings in school or games, a good habit is…",
    choices: ["Listen carefully, avoid stereotypes, and remember cultures are living", "Copy sacred ceremonies as costumes for fun", "Assume one story fits every Nation", "Treat all Native people as characters from the 1800s only"],
    a: 0,
    hint: "Respect > performance.",
    teach: "There are many Nations and teachings. Curiosity plus humility is the right trail gear.",
  },
  {
    id: "q-canoe-family",
    topic: "Travel",
    q: "Who typically traveled the water roads?",
    choices: ["Families, traders, diplomats, and messengers — whole communities on the move", "Only solitary pirates", "Only children without adults", "Only animals riding logs"],
    a: 0,
    hint: "Travel connected kinship and diplomacy.",
    teach: "Canoe routes carried people and relationships, not just cargo.",
  },
  {
    id: "q-fish-stew",
    topic: "Foodways",
    q: "Why are lakes and rivers central to food stories here?",
    choices: ["Fish, wild rice, water plants, and travel all depend on healthy waters", "Because water is only for swimming races", "Because food never comes from water", "Because rivers are made of syrup"],
    a: 0,
    hint: "Water = life + movement + harvest.",
    teach: "Caring for water protects foodways and future travelers.",
  },
  {
    id: "q-story-bundle",
    topic: "Stories",
    q: "In this game, a Story Stone stands for…",
    choices: ["A piece of knowledge you learned and carry forward", "A rock you throw at canoes", "A video-game coin with no meaning", "A ticket for a roller coaster"],
    a: 0,
    hint: "You gather understanding, not just points.",
    teach: "Carrying stories — like carrying a canoe — takes care, memory, and sharing.",
  },
  {
    id: "q-three-sisters-not",
    topic: "Foodways",
    q: "Maple sugar and manoomin are important here. Which statement is true?",
    choices: ["They are part of living food traditions, not only museum exhibits", "They were invented by French explorers alone", "They only exist in cartoons", "They are illegal to talk about"],
    a: 0,
    hint: "People still sugar and rice today.",
    teach: "Food traditions continue in families and communities across the seasons.",
  },
  {
    id: "q-fort-context",
    topic: "History",
    q: "When you hear about forts near river meetings, what should you also remember?",
    choices: ["Indigenous places and meanings were already there", "The land was empty until a fort appeared", "Rivers began after forts were built", "Only forts matter in history class"],
    a: 0,
    hint: "Start the timeline earlier.",
    teach: "Forts are one layer. Homelands, treaties, and living Nations are the deeper story.",
  },
  {
    id: "q-beaver",
    topic: "Land",
    q: "Beavers matter in this landscape because they…",
    choices: ["Build dams that change waterways — and their fur was also traded", "Are mythical and never real", "Only live in the ocean", "Eat birchbark canoes for breakfast exclusively"],
    a: 0,
    hint: "Engineers of wetlands + fur trade history.",
    teach: "Animals shape land and stories; the fur trade also entangled human economies.",
  },
  {
    id: "q-winter",
    topic: "Seasons",
    q: "How did winter change travel and life on the trail?",
    choices: ["Snow and ice meant different routes, foods, and skills — like snowshoes and stored foods", "Everyone stopped existing until spring", "Canoes flew instead of floated", "Winter never happens in Minnesota"],
    a: 0,
    hint: "Seasons demand different knowledge.",
    teach: "Winter skills and stored foods were as important as summer paddling.",
  },
  {
    id: "q-treaty-aware",
    topic: "History",
    q: "Treaties between Native Nations and the U.S. are best understood as…",
    choices: ["Serious nation-to-nation agreements with lasting importance", "Silly handshake jokes", "Rules that only applied for one afternoon", "Something that erased all Native rights forever automatically"],
    a: 0,
    hint: "Treaties are law and living politics — learn more with teachers and elders.",
    teach: "Treaty history is complex. This game only opens the door — keep learning with trusted sources.",
  },
  {
    id: "q-loon",
    topic: "Land",
    q: "The common loon's call is famous on northern lakes. What does that remind us?",
    choices: ["Healthy lakes support wildlife people have long lived beside", "Loons are robots", "Lakes are silent places with no animals", "Birds only live in cities"],
    a: 0,
    hint: "Soundscape of the north woods.",
    teach: "People and animals share these waters — stewardship matters.",
  },
  {
    id: "q-copper",
    topic: "Exchange",
    q: "Native peoples of the Great Lakes region worked copper long ago. What does that show?",
    choices: ["Advanced skill, trade, and technology were present for a very long time", "Metalwork began only after 1900 here", "Copper was useless", "Only Europeans ever used copper"],
    a: 0,
    hint: "Ancient mines and trade goods tell a deep timeline.",
    teach: "Innovation and trade are part of Indigenous history in this region.",
  },
  {
    id: "q-women-rice",
    topic: "Foodways",
    q: "Harvesting and processing manoomin often involves…",
    choices: ["Community knowledge, care, and shared work across generations", "One person guessing with no teaching", "Throwing rice away", "Only machines with no people"],
    a: 0,
    hint: "Knowledge is taught and practiced together.",
    teach: "Foodways are community practices — skills passed with patience.",
  },
  {
    id: "q-maps",
    topic: "Travel",
    q: "Indigenous maps and knowledge of routes were often carried how?",
    choices: ["In memory, story, song, and teaching — sometimes also in drawings", "Only on smartphone GPS", "Never — people wandered randomly", "Only written in English books"],
    a: 0,
    hint: "Oral and practiced knowledge is powerful.",
    teach: "Knowing water roads was (and is) a sophisticated skill.",
  },
  {
    id: "q-kids",
    topic: "People",
    q: "Kids on the historical trail would most likely have…",
    choices: ["Learned skills by helping family — paddling, gathering, listening to stories", "Been banned from all outdoor knowledge", "Only played indoors forever", "Run the fur companies alone as CEOs"],
    a: 0,
    hint: "Learning by doing beside elders and relatives.",
    teach: "Young people have always been part of the seasonal round and story-carrying.",
  },
  {
    id: "q-mississippi-link",
    topic: "Places",
    q: "The St. Croix joins a larger river system that includes…",
    choices: ["The Mississippi River", "The Nile only", "The Amazon only", "No other rivers"],
    a: 0,
    hint: "Southward waters gather into a famous North American river.",
    teach: "Local valleys connect to continental water roads — geography is relationship.",
  },
  {
    id: "q-stereotype",
    topic: "Care",
    q: "Which choice avoids a harmful stereotype?",
    choices: ["Native Nations are diverse, modern, and rooted in specific places and languages", "All Native people are the same and live only in the past", "Native cultures are costumes for parties", "Native history starts only when settlers arrive"],
    a: 0,
    hint: "Specific > generic.",
    teach: "This game focuses on Dakota and Ojibwe connections to the St. Croix — still only a beginning.",
  },
  {
    id: "q-bundle",
    topic: "Stories",
    q: "A birchbark Story Bundle in this game is a metaphor for…",
    choices: ["Carrying knowledge carefully to share at the Council", "A lunchbox that never opens", "A weapon", "A GPS device"],
    a: 0,
    hint: "Portage = carry canoe + carry stories.",
    teach: "You win by learning and sharing, not by erasing others' stories.",
  },
  {
    id: "q-energy",
    topic: "Travel",
    q: "Why did travelers care about food energy on a portage?",
    choices: ["Carrying canoes is hard work — meals and rest keep people going", "Food was only for decoration", "Portages take zero effort", "Energy bars were sold by every glacier"],
    a: 0,
    hint: "Heavy canoe + muddy trail = teamwork and snacks.",
    teach: "Logistics — food, rest, and shared labor — made long journeys possible.",
  },
];

export function drawStoryCard(usedIds = []) {
  const used = new Set(usedIds);
  let pool = STORY_DECK.filter((c) => !used.has(c.id));
  let reshuffled = false;
  if (!pool.length) {
    pool = [...STORY_DECK];
    reshuffled = true;
  }
  const card = shuffle(pool)[0];
  const mixed = shuffleChoices(card.choices, card.a);
  return {
    card: {
      id: card.id,
      topic: card.topic,
      q: card.q,
      hint: card.hint,
      teach: card.teach,
      choices: mixed.choices,
      answer: mixed.answer,
    },
    usedIds: reshuffled ? [card.id] : [...usedIds, card.id],
    reshuffled,
  };
}

export function deckRemaining(usedIds = []) {
  return Math.max(0, STORY_DECK.length - usedIds.length);
}
